### ISSUE TITLE
ValueError: No such layer: bn5c_branch2c.

### ISSUE THREAD

**Issue by pratikadarsh** [Chris10M/RFB-Text-Detection#10]
So I downloaded the model from the google drive link mentioned in the readme. On running the run_demo.py code I get the following error:

Traceback (most recent call last):
  File "run_demo.py", line 113, in <module>
    rfb_text_model = RFBText(model_weights_path=model_path)()
  File "/media/sf_ubuntu_shared/text_detection/RFB-Text-Detection/model.py", line 153, in __call__
    model =  self.build()
  File "/media/sf_ubuntu_shared/text_detection/RFB-Text-Detection/model.py", line 112, in build
    C5 =  self.backbone.get_layer('bn5c_branch2c').output
  File "/home/pratik/.virtualenvs/tf_2.0-keras/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 2398, in get_layer
    raise ValueError('No such layer: ' + name + '.')
ValueError: No such layer: bn5c_branch2c.

Any help would be great. Thanks.

**Comment by pratikadarsh** [comment]
Ok so my bad, I was trying this on tf2.x where keras.application codes further import from tensorflow.keras.applications. Hence the error.
